### PR TITLE
Add jazzy

### PR DESCRIPTION
**Pull request by christophfroehlich**
let sphinx-multiversion create a page for Jazzy Jalisco, pointing to all rolling/master subrepos. 
fyi: There is already one at https://docs.ros.org/

### CODE REVIEW

**Review by saikishor — APPROVED** [review]
@christophfroehlich The changes itself look good to me. 
Maybe it is better to wait until the Tutorial party is done, before merging this

**Comment by christophfroehlich** [comment]
@saikishor there is no hurry for merging it, but there won't be any changes necessary unless we branch the subrepos for jazzy

**Comment by saikishor** [comment]
> @saikishor there is no hurry for merging it, but there won't be any changes necessary unless we branch the subrepos for jazzy

Ofcourse, I agree. If that's the case, we can then merge it.

**Comment by christophfroehlich** [comment]
Let's wait until Jazzy is included in index.ros.org and docs.ros.org/api

**Review by fmauch — APPROVED** [review]
The changes seem correct to me though I haven't fully understood the multiversion build, yet.

**Comment by christophfroehlich** [comment]
> The changes seem correct to me though I haven't fully understood the multiversion build, yet.

The core setting is the `smv_branch_whitelist`: Every branch matching this regex will be built as a version during multiversion build. The other stuff is only for auto-replacement of macros in the docs, as well as checkout the correct branches of the subrepos.

**Comment by christophfroehlich** [comment]
After merging this, I'll rename the default branch of this repo from master to rolling (similar to https://github.com/ros2/ros2_documentation) to make sphinx-multiversion write "Rolling" instead of "Master"

Edit: This will not break old links, I copied the "master" html folder so that one will at least reach something useful.

image

**Pull request merged**
