### PR TITLE
Add humble as latest version

### LINKED ISSUE #76: Version for humble
I don't have a detailed overview, but some rolling-pages might be already incorrect for humble. 

At least one example is the [JTC](https://control.ros.org/master/doc/ros2_controllers/joint_trajectory_controller/doc/userdoc.html) doc.

### PR DESCRIPTION
**Pull request by christophfroehlich**
New to sphinx, what else do I have to change?
- in this master branch
- in a still-to-be-added humble branch: the title in index.rst, and lines 34-37 in conf.py is enough?
- in the other branches: conf.py?

This does not build now, because ros2_control_demos does not have a humble branch yet.

Closes #76

### CODE REVIEW

**Comment by destogl** [comment]
@mamueluth can you give it a check?

**Review by destogl — APPROVED** [review]

**Comment by destogl** [comment]
The issue is that ros2_control_demos does not have `humble` branch. Do we need it there?

**Comment by christophfroehlich** [comment]
Until now we don't need a humble-branch in the demo repository, but maybe this is changing soon with iron release and ABI/API breaking stuff.
I just did not know how to fix that multiversion sphinx config without a humble branch everywhere ;)

**Comment by mamueluth** [comment]
I think there aren't more changes needed.

If you want to have different branches checked out for different sub-repos the easiest thing to do would be to declare for ros2_controllers and ros2_control_demos their own mapping for branches in deploy_defines. Then use this mapping [here](https://github.com/ros-controls/control.ros.org/blob/b5f275ae9ce9e0a04dcffe3540d1e01383a3b67b/make_help_scripts/add_tmp_commits#L21-L24l)

**Comment by christophfroehlich** [comment]
Thanks for the comment. If we add a humble branch for the demos, then we don't need a special mapping here.

**Comment by christophfroehlich** [comment]
As we have now the `humble` branch on ros2_control_demos repo, sphinx from this PR builds now and can go live.

**Comment by bmagyar** [comment]
And you can reach the humble deployment already at https://control.ros.org/humble/index.html 

Thanks!

**Pull request merged**
