### PR TITLE
Add MuJoCo by FZI and AlgoryX

### PR DESCRIPTION
**Pull request by christophfroehlich**
ros2_control system interface for MuJoCo. Not tested but looks great!

### CODE REVIEW

**Comment by christophfroehlich** [comment]
@mergifyio backport humble iron

**Comment by stefanscherzinger** [comment]
@christophfroehlich 

Thanks for spotting and referencing that implementation! However, I'm afraid that's *a little* robot dependent at the moment. As far as I'm concerned, MuJoCo needs a specific configuration *.xml* that specifies the robot to simulate. We could adapt/change it to provide a more generic interface between MuJoCo and ros2_control so that users can simulate arbitrary robots (manipulators). I didn't continue this idea lately, but I'm interested in supporting/implementing if that's of use for the community.

**Comment by christophfroehlich** [comment]
> @christophfroehlich
> 
> Thanks for spotting and referencing that implementation! However, I'm afraid that's _a little_ robot dependent at the moment. As far as I'm concerned, MuJoCo needs a specific configuration _.xml_ that specifies the robot to simulate. We could adapt/change it to provide a more generic interface between MuJoCo and ros2_control so that users can simulate arbitrary robots (manipulators). I didn't continue this idea lately, but I'm interested in supporting/implementing if that's of use for the community.

For the scope of this PR it is fine like it is. It should just give a reference implementation for users on control.ros.org

I have a personal interest in bringing MuJoCo and ros2_control closer due to a research project I'm working on. But I haven't tried it out yet and can't comment on the limitations. @traversaro pointed me to https://github.com/google-deepmind/mujoco/issues/1432, so I think there is more work to be done to provide a seamless integration like with Gazebo (classic). Once I have the time to work on that, I'd be happy to discuss future steps to find a more general solution.

**Comment by traversaro** [comment]
> @traversaro pointed me to [google-deepmind/mujoco#1432](https://github.com/google-deepmind/mujoco/issues/1432), so I think there is more work to be done to provide a seamless integration like with Gazebo (classic). Once I have the time to work on that, I'd be happy to discuss future steps to find a more general solution.

Just to complement the link, I think most of people using URDF with MuJoCo either manually or automatically change the URDF before the loading in MuJoCo, or the resulting `.mjcf` after the conversion,  and that is why there are not a lot of discussion like https://github.com/google-deepmind/mujoco/issues/1432 in MuJoCo issue tracker.

**Pull request merged**
