### PR TITLE
Substitution of branch names

### PR DESCRIPTION
**Pull request by christophfroehlich**
I realized that the extension used from #85 works only in the preamble but not within directives, i.e., refs/links etc.
I reverted that change and propose the usage of the already existing macro `expand_macros` connected to the `source-read` event of sphinx: The key `{REPOS_FILE_BRANCH}` was already existing, and works now everywhere as far as I know.

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
Do we need to update the foxy branch?

**Comment by christophfroehlich** [comment]
I'm not sure why CI fails now, `sphinxcontrib.globalsubs` is not included explicitly anywhere now.

**Comment by christophfroehlich** [comment]
> Do we need to update the foxy branch?

I think the conf.py is only used from the master branch, but the links could be updated in foxy etc

**Comment by christophfroehlich** [comment]
And we have to merge the linked PRs first, otherwise the not-any-more-existing substitution will fail.

**Comment by bmagyar** [comment]
But if there's a deployment between merging the linked PRs and this, there will be broken links on the page for a short amount of time, ja?

**Comment by christophfroehlich** [comment]
No, the "new" method was already there before. Merging the linked PRs won't
break anything

Bence Magyar ***@***.***> schrieb am Di., 23. Mai 2023, 18:09:

**Review by destogl — APPROVED** [review]
Can be merged when CI is happy

**Comment by christophfroehlich** [comment]
If I'd know why it is failing 🤔

**Comment by christophfroehlich** [comment]
ros2_control_demos was published successfully with the latest changes. lets merge the PRs in the other two repos, then I'll try to fix the failing CI. maybe this is an artefact of the build script, which checks out the master branch instead of the one from the PR, where the missing requirement was not installed from.

**Comment by bmagyar** [comment]
Branches merged

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
