### PR TITLE
Add precommit

### PR DESCRIPTION
**Pull request by bmagyar**
Please opinionate whether I should add/remove checkers or add filters for things.

For example: I think .po files could probably be left untouched, I can remove those changes and add filters.

### CODE REVIEW

**Review by jaron-l — COMMENTED** [review]
What about adding a code formatter? Like black, autopep8, etc.

**Comment by bmagyar** [comment]
we don't host functional code in the repo

**Review by destogl — CHANGES_REQUESTED** [review]
add ci config

**Review by jaron-l — APPROVED** [review]

**Comment by bmagyar** [comment]
I finally managed to get around and add the CI config for the format stage

**Review by christophfroehlich — APPROVED** [review]
Great! And it builds fine with almost no errors ;)

**Review by destogl — CHANGES_REQUESTED** [review]

**Comment by bmagyar** [comment]
I'll remove the this party changes tomorrow from the PR

**Review by destogl — APPROVED** [review]
Very useful and cool! Thanks for keeping to push on this!

**Pull request merged**
