### PR TITLE
Delete 2022-12_ROS-I_Conference-ros2_control_-_Kernel_for_ROS_2_contr…

### PR DESCRIPTION
**Pull request by destogl**
…olled_robots.pdf

### CODE REVIEW

**Comment by bmagyar** [comment]
Why?

**Comment by destogl** [comment]
Because it is now working. The file has error...

I am trying to add another one, but it just doesn't want...

The problem is that he file is big because it has embedded videos (which is very cool!). Maybe I don't understand something with GH and git LFS and public repos...

Have to check and try one more time.

Or should we host files somewhere else?

**Comment by bmagyar** [comment]
PDFs are ok but we shouldn't host videos inside IMO

**Comment by destogl** [comment]
> PDFs are ok but we shouldn't host videos inside IMO

Sad, they are so nicely embeded :D

**Pull request merged**
