### PR TITLE
Add tabs extension

### PR DESCRIPTION
**Pull request by christophfroehlich**
Enable tabs (known from docs.ros.org)

### CODE REVIEW

**Comment by christophfroehlich** [comment]
@mergifyio backport humble iron

**Comment by bmagyar** [comment]
Do you have a screenshot?

**Comment by christophfroehlich** [comment]
image

I used it only once in the linked PR. But I was thinking of using it in the demos repository for the parallel local/docker file instructions.

**Review by bmagyar — APPROVED** [review]
Seems pretty useful to me, thanks!

**Pull request merged**
