### PR TITLE
updated vcs import file name in getting_started.rst

### PR DESCRIPTION
**Pull request by VineetTambe**
updated vcs import file name from ros2_control.repos to ros2_control.humble.repos

### CODE REVIEW

**Review by christophfroehlich — APPROVED** [review]
Thanks. However, the repos files are not complete and the build from source won't work with this single file :/

**Comment by VineetTambe** [comment]
Is there any way I can help out with that?
Could you outline what all would be required for it to be deemed completed? 
I would like to contribute.

**Comment by christophfroehlich** [comment]
I already discussed this briefly with @bmagyar, the repos file are somewhere necessary for the CI but not intended for installation.
We would need a complete file like [here](https://github.com/christophfroehlich/ros2_rolling_ws/blob/master/ros_control.repos), but I don't know where we would include this.

**Comment by christophfroehlich** [comment]
@fmauch already addressed this with #102

**Pull request merged**
