### PR TITLE
Add contributions to acknowledgement page

### PR DESCRIPTION
**Pull request by christophfroehlich**
As requested by @bmagyar ;) 

I suggest using tabs for the multiple tables now. Any preferences on what showing on top?

image

Implementation detail: the tabs.js from https://github.com/executablebooks/sphinx-tabs does not work with jQuery, I added it manually here and commented the last lines.
https://github.com/executablebooks/sphinx-tabs/issues/189

### CODE REVIEW

**Comment by christophfroehlich** [comment]
Btw: I just skip commits without authors, which means normally that the account doesn't exist (any more).

**Comment by destogl** [comment]
I suggest to add something to `12 Months` tabs so one can recognize them. It could be something short like `12 Months Rev` and `12 Months Contrib`  or even `12 Mo Reviews`..., what do you think? I would start with contributions in the last 12 months.

**Comment by christophfroehlich** [comment]
> I suggest to add something to `12 Months` tabs so one can recognize them. It could be something short like `12 Months Rev` and `12 Months Contrib` or even `12 Mo Reviews`..., what do you think? I would start with contributions in the last 12 months.

I thought about the same, but I mean it is obviously after the second click ;) But I add something and change the default tab

**Comment by christophfroehlich** [comment]
@destogl I updated the tabs, see the screenshot above. The only thing I'm not sure about is how well the tabs work with responsive design on mobile phones.

**Review by destogl — APPROVED** [review]

**Comment by destogl** [comment]
You are welcome to merge at your convenience when check are passing. I am not sure if there is an error, or data is not available yet and will be later.

**Comment by christophfroehlich** [comment]
Exactly, data is not available yet. and cache from PRs can't be accessed from master workflows -> cancelled.

**Comment by christophfroehlich** [comment]
@mergifyio backport humble iron

**Pull request merged**
